version: '3.9'

services:
  postgres:
    image: postgres:latest
    container_name: example-db
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
     - ../.env
  redis:
    image: redis/redis-stack:latest
    container_name: redis-stack
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
      - "${REDIS_LOCAL_PORT}:${REDIS_LOCAL_PORT}"
    volumes:
      - redis-data:/data
    env_file:
     - ../.env

volumes:
  postgres_data:
  redis-data:
